//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Answer
{
    public int sid { get; set; }
    public int labid { get; set; }
    public int surveyid { get; set; }
    public int qid { get; set; }
    public int studentid { get; set; }
    public string contents { get; set; }
    public string phase { get; set; }
    public string opinions { get; set; }
    public string links { get; set; }
    public Nullable<int> rank { get; set; }
    public Nullable<int> optionid { get; set; }

    public virtual Lab Lab { get; set; }
    public virtual Question Question { get; set; }
    public virtual Survey Survey { get; set; }
    public virtual User User { get; set; }
}

public partial class DiscussionA
{
    public DiscussionA()
    {
        this.DiscussionA1 = new HashSet<DiscussionA>();
        this.DiscussionAFeedbacks = new HashSet<DiscussionAFeedback>();
    }

    public int sid { get; set; }
    public int labid { get; set; }
    public int groupid { get; set; }
    public string topic { get; set; }
    public Nullable<int> topicid { get; set; }
    public int student_id { get; set; }
    public Nullable<System.DateTime> time { get; set; }

    public virtual ICollection<DiscussionA> DiscussionA1 { get; set; }
    public virtual DiscussionA DiscussionA2 { get; set; }
    public virtual Lab Lab { get; set; }
    public virtual User User { get; set; }
    public virtual ICollection<DiscussionAFeedback> DiscussionAFeedbacks { get; set; }
}

public partial class DiscussionAFeedback
{
    public int discuss_id { get; set; }
    public int sid { get; set; }
    public int student_id { get; set; }
    public string gfeedback { get; set; }
    public string qfeedback { get; set; }

    public virtual DiscussionA DiscussionA { get; set; }
}

public partial class DiscussionB
{
    public int sid { get; set; }
    public int labid { get; set; }
    public int groupid { get; set; }
    public string topic { get; set; }
    public int student_id { get; set; }
    public Nullable<System.DateTime> time { get; set; }

    public virtual Lab Lab { get; set; }
    public virtual User User { get; set; }
}

public partial class Lab
{
    public Lab()
    {
        this.Answers = new HashSet<Answer>();
        this.DiscussionAs = new HashSet<DiscussionA>();
        this.DiscussionBs = new HashSet<DiscussionB>();
        this.ScaleAnswers = new HashSet<ScaleAnswer>();
        this.Status = new HashSet<Status>();
        this.Surveys = new HashSet<Survey>();
        this.Users = new HashSet<User>();
    }

    public int sid { get; set; }
    public string name { get; set; }
    public string desc { get; set; }
    public string currentPhase { get; set; }
    public System.DateTime begin { get; set; }
    public System.DateTime end { get; set; }

    public virtual ICollection<Answer> Answers { get; set; }
    public virtual ICollection<DiscussionA> DiscussionAs { get; set; }
    public virtual ICollection<DiscussionB> DiscussionBs { get; set; }
    public virtual ICollection<ScaleAnswer> ScaleAnswers { get; set; }
    public virtual ICollection<Status> Status { get; set; }
    public virtual ICollection<Survey> Surveys { get; set; }
    public virtual ICollection<User> Users { get; set; }
}

public partial class Question
{
    public Question()
    {
        this.Answers = new HashSet<Answer>();
        this.ScaleAnswers = new HashSet<ScaleAnswer>();
    }

    public int sid { get; set; }
    public string question1 { get; set; }
    public int survryid { get; set; }
    public int no { get; set; }

    public virtual ICollection<Answer> Answers { get; set; }
    public virtual Survey Survey { get; set; }
    public virtual ICollection<ScaleAnswer> ScaleAnswers { get; set; }
}

public partial class ScaleAnswer
{
    public int sid { get; set; }
    public int labid { get; set; }
    public int surveyid { get; set; }
    public int qid { get; set; }
    public int studentid { get; set; }
    public Nullable<int> rank { get; set; }

    public virtual Lab Lab { get; set; }
    public virtual Question Question { get; set; }
    public virtual Survey Survey { get; set; }
    public virtual User User { get; set; }
}

public partial class Status
{
    public int sid { get; set; }
    public int labid { get; set; }
    public string phase { get; set; }
    public int studentid { get; set; }
    public bool done { get; set; }

    public virtual Lab Lab { get; set; }
    public virtual User User { get; set; }
}

public partial class Survey
{
    public Survey()
    {
        this.Answers = new HashSet<Answer>();
        this.Questions = new HashSet<Question>();
        this.ScaleAnswers = new HashSet<ScaleAnswer>();
    }

    public int sid { get; set; }
    public string name { get; set; }
    public string phase { get; set; }
    public string type { get; set; }
    public string scale { get; set; }
    public int surveyid { get; set; }
    public int labid { get; set; }
    public string desc { get; set; }
    public string title { get; set; }

    public virtual ICollection<Answer> Answers { get; set; }
    public virtual Lab Lab { get; set; }
    public virtual ICollection<Question> Questions { get; set; }
    public virtual ICollection<ScaleAnswer> ScaleAnswers { get; set; }
}

public partial class User
{
    public User()
    {
        this.Answers = new HashSet<Answer>();
        this.DiscussionAs = new HashSet<DiscussionA>();
        this.DiscussionBs = new HashSet<DiscussionB>();
        this.ScaleAnswers = new HashSet<ScaleAnswer>();
        this.Status = new HashSet<Status>();
    }

    public int sid { get; set; }
    public string name { get; set; }
    public string nickname { get; set; }
    public string passsword { get; set; }
    public Nullable<System.DateTime> birthday { get; set; }
    public int age { get; set; }
    public string group { get; set; }
    public string school { get; set; }
    public string dept { get; set; }
    public int labid { get; set; }
    public string student_id { get; set; }
    public Nullable<int> groupid { get; set; }
    public string gender { get; set; }

    public virtual ICollection<Answer> Answers { get; set; }
    public virtual ICollection<DiscussionA> DiscussionAs { get; set; }
    public virtual ICollection<DiscussionB> DiscussionBs { get; set; }
    public virtual Lab Lab { get; set; }
    public virtual ICollection<ScaleAnswer> ScaleAnswers { get; set; }
    public virtual ICollection<Status> Status { get; set; }
}
