//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class LabsDBEntities : DbContext
{
    public LabsDBEntities()
        : base("name=LabsDBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Answer> Answers { get; set; }
    public DbSet<DiscussionA> DiscussionAs { get; set; }
    public DbSet<DiscussionAFeedback> DiscussionAFeedbacks { get; set; }
    public DbSet<DiscussionB> DiscussionBs { get; set; }
    public DbSet<Lab> Labs { get; set; }
    public DbSet<Question> Questions { get; set; }
    public DbSet<ScaleAnswer> ScaleAnswers { get; set; }
    public DbSet<Status> Status { get; set; }
    public DbSet<Survey> Surveys { get; set; }
    public DbSet<sysdiagram> sysdiagrams { get; set; }
    public DbSet<User> Users { get; set; }
}
